---
- name: Instalar Capa de Base de Datos
  hosts: "*db*"  # <--- FILTRO POR PATRÓN DE NOMBRE
  become: yes
  tasks:
    - name: Instalar servidor MariaDB
      dnf:
        name: mariadb-server
        state: present

    - name: Iniciar servicio MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
