---
- name: Instalar Capa de Base de Datos
  hosts: all
  become: yes
  tasks:
    - name: Instalar servidor MariaDB
      dnf:
        name: mariadb-server
        state: present

    - name: Iniciar servicio MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Crear base de datos dummy
      command: touch /var/lib/mysql/app_db_initialized
      args:
        creates: /var/lib/mysql/app_db_initialized
