---
- name: Instalar Capa de Aplicación
  hosts: "*app*" # <--- SOLO EJECUTA EN SERVIDORES 'APP'
  become: yes
  tasks:
    - name: Instalar PHP y dependencias
      dnf:
        name: 
          - php
          - php-cli
          - php-mysqlnd
        state: present

    - name: Crear config dummy
      copy:
        dest: /etc/myapp_config.ini
        content: "db_host=db-server"
