---
- name: Instalar Capa Web
  hosts: all
  gather_facts: no # Para que sea rápido
  tasks:
    - name: Expulsar a los que no son Web
      meta: end_host
      when: "'web' not in inventory_hostname"

    - name: Tareas reales (Solo llegarán aquí los web)
      block:
        - name: Instalar Apache
          dnf: ...
      # No necesitas 'when' aquí porque los demás ya fueron expulsados
