---
- name: Instalar Capa Web (Frontend)
  hosts: all
  become: yes
  tasks:
    - name: Instalar Apache Web Server
      dnf:
        name: httpd
        state: present

    - name: Iniciar servicio Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Crear index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Aplicacion Desplegada por AWX Workflows</h1>"
