---
- name: Instalar Capa Web
  hosts: all  # Dejamos que entre todo el mundo
  become: yes
  tasks:
    - name: Instalar Apache
      dnf:
        name: httpd
        state: present
      # LA LÓGICA MÁGICA: Solo ejecuta si 'web' es parte del nombre
      when: "'web' in inventory_hostname"

    - name: Iniciar Apache
      service:
        name: httpd
        state: started
        enabled: yes
      when: "'web' in inventory_hostname"
